### ISSUE TITLE
Unusual behaviour in Cinema4D R21 + Octane Studio 2022.1?

### ISSUE THREAD

**Issue by v60coffee** [MrLixm/AgXc#12]

**Comment by v60coffee** [comment]
Hello. Maybe I am doing something incorrectly, but I use the same steps I did with with OCIO v 1.2.
Uploaded "ocio" folder into "C:\Program Files\Maxon Cinema 4D R21\plugins" folder. Then in Octane setings I changed the folder of Config file from ocio1_2 to a new folder and file "C:\Program Files\Maxon Cinema 4D R21\plugins\ocio\config.ocio". 

![agxc-oc](https://user-images.githubusercontent.com/9624328/207169774-8f6087d1-c4dd-46ac-af99-456ca882838c.png)

Is the green field correctly set up? Or do I have to choose something manually there?

As for the other OCIO setting, I have tried this:

![agxc-oc1](https://user-images.githubusercontent.com/9624328/207170249-de9849a1-689d-45ab-9da6-fbe6898f6206.png)

And what do I have to choose in Export setting there? Seems there is no AgX there? Am I missing some step?

![agxc-oc2](https://user-images.githubusercontent.com/9624328/207170824-c04bc489-18d3-41e1-89b6-37663489603e.png)

Thank you.

**Comment by MrLixm** [comment]
Hello there, 
I'm sorry but I cannot help you as I'm unfamiliar with C4D and Octane.

First thing though, is that the way you change the OCIO config is not the right way. Right now you are overriding the default installation file which is clearly not a good thing. You should never touch the file in the application installation directory.

To set OCIO you usually have to set an environment variable that points to the path of the config, which can be anywhere on your disk.

To not leave you like that I can still share with some very good resources that might help you (it explain how to set the environment variable) :

- https://www.elsksa.me/scientia/cgi-offline-rendering/octane-render-color-management
- https://www.elsksa.me/scientia/cgi-offline-rendering/octane-render-aces

If that is good with you I am going to close this issue as I can't help you more and this is not an issue with AgX ?

**Comment by v60coffee** [comment]
Yes, I have been reading those links for several weeks over and over again, but these texts there are rather cryptic. Reads like random thoughts and unconnected bits of wisdom. :) There are no clear step-by-step recommendations there—best practice way. But thank you for the quick reply, I will try to get there through trial and error then. Please close the issue and thank you again.

**Comment by MrLixm** [comment]
Thanks, good luck with that !
