### ISSUE TITLE
Increase compatibility with Redshift.

### ISSUE THREAD

**Issue by MrLixm** [MrLixm/AgXc#2]
# Update
A thread has been opened on the Redshift forum 
> https://redshift.maxon.net/topic/44651/ocio-colorspace-discovering-process-is-too-obscure

# Original issue

_(Info initally provided by Saul Espinoza)_
When parsing config, Redshift will be looking for the "sRGB EOTF" colorspace to perform some transformations when needed.
The discovery process is hardcoded and not very clear yet but seems you need a colorspace named with at least "sRGB" in the name 
and then a specific transform. (probably does a regex on values or on transform name ?)
Saul recommended to try first the true EOTF with
```
- !<ExponentWithLinearTransform> {gamma: 2.4, offset: 0.055, direction: inverse}
```
But let's also try the power function to see if its looking for the ExponentTransform or for the "2.4" value.
```
-!<ExponentTransform> { value: [ 2.2, 2.2, 2.2, 1 ], direction: inverse }
```

**Comment by MrLixm** [comment]
Trying to reproduce the error in katana.

Error message related seems to be :

```
[...] (kind of at the end of the logs)
[INFO plugins.Redshift]: Creating OCIO processors between rendering and view/srgb spaces
[INFO plugins.Redshift]: 	Rendering space: Linear sRGB
[INFO plugins.Redshift]: 	Display: sRGB
[INFO plugins.Redshift]: 	View: AgX Punchy
[WARN plugins.Redshift]: 	Failed to find a suitable sRGB color space in config!
[INFO plugins.Redshift]: 		Proxies with textures in 'sRGB' color space may not render correctly.
[INFO plugins.Redshift]: 		Physical sun/sky, black-body and hair shaders may not render correctly.
[WARN plugins.Redshift]: 	Failed to create rendering to sRGB processor
```

I also have a warning for the sRGB linear variant :

```
[INFO plugins.Redshift]: Loading OCIO config using .\ocio\config.ocio
[INFO plugins.Redshift]: 	OCIO env var defined. Using it instead
[INFO plugins.Redshift]: 	Full path: .\ocio\config.ocio
[INFO plugins.Redshift]: 	Ok
[INFO plugins.Redshift]: Creating OCIO processors between rendering and view/srgb spaces
[INFO plugins.Redshift]: 	Rendering space: Linear sRGB
[INFO plugins.Redshift]: 	Display: sRGB
[INFO plugins.Redshift]: 	View: AgX Punchy
[WARN plugins.Redshift]: 	Failed to find a suitable sRGB color space in config!
[INFO plugins.Redshift]: 		Proxies with textures in 'sRGB' color space may not render correctly.
[INFO plugins.Redshift]: 		Physical sun/sky, black-body and hair shaders may not render correctly.
[WARN plugins.Redshift]: 	Failed to create rendering to sRGB processor
[INFO plugins.Redshift]: Loading OCIO color space transforms for texture sampling
[INFO plugins.Redshift]: 	Unable to find a suitable sRGB-linear color space. Common texture linear color space will be: "Linear sRGB"
[INFO plugins.Redshift]: Render command finished. Returning to Katana a non-zero render result.
```

**Comment by MrLixm** [comment]
Manage to reproduce the issue in C4D 2023 :

# Steps

- Set OCIO var with config
- Open C4d
- RenderSettings > Renderer > Redshift
- Add new light > Dome light
- Small log window open mentioning an OCIO error, I then open the corresponding log file.
```
14:22:03   2581MB DEBUG: OCIO: Loaded Config 'Z:\packages-dev\AgXc\ocio\config.ocio'
14:22:03   2592MB ERROR: OCIO: Could not determine common color-spaces for config 'Z:\packages-dev\AgXc\ocio\config.ocio'
14:22:03   2594MB DEBUG: OCIO: Could not open OCIO config at ''  
```

# First fix

By adding the colorspace mentioned by Saul the error disappears:
- In the config.ocio
- Change OCIO version header to 2
- Add the "sRGB - curve" colorspace :
```yaml
  - !<ColorSpace>
   name: sRGB - Curve
   family: Displays/SDR
   equalitygroup: ""
   bitdepth: unknown
   description: sRGB - Curve
   isdata: false
   allocation: uniform
   from_scene_reference: !<GroupTransform>
     children:
       - !<ExponentWithLinearTransform> {gamma: 2.4, offset: 0.055, direction: inverse}
       - !<RangeTransform> {min_in_value: 0., min_out_value: 0., max_in_value: 1., max_out_value: 1.}
```

But this fix is only for v2 config and I must maintain v1 compatibility

**Comment by MrLixm** [comment]
# How Redshift detects the "sRGB" colorspace.

After some tests seems Redshift expect any kind of colorspace with at least this exact transform:
```yaml
- !<ExponentWithLinearTransform> {gamma: 2.4, offset: 0.055, direction: inverse}
```
Where that gamma value matters, and you can't use a classical `ExponentTransform`.
The name/description/family of the colorspace doesn't matter.

**Comment by MrLixm** [comment]
# How Redshift detects the "sRGB" colorspace : Results

Redshift need 3 colorspaces to work : "LinearSRGB", "SRGB", "Raw"

- Roles matter, as you can see in the minimal working examples, colorspaces names doesn't matter but roles does.
- For the sRGB colorspace, the transform matters, picked transform are :
    - `<FileTransform>` solo
    - `<ExponentWithLinearTransform> {gamme: 2.4, ...}` IF only in a `GroupTransform`

**Comment by pbrt4bounty** [comment]
Try you to make a look into the shipped OCIO files for Blender addon to see how  a custom config is adapted to use in RS.

**Comment by MrLixm** [comment]
Nice tip thanks ! Seems to be using the `!<FileTransform> {src: srgb.spi1d, interpolation: linear}` as in the substance config for the `sRGB` colorspace so that make it clear why this transform is being used to identify the sRGB colorspace, because the Blender config has it.

**Comment by MrLixm** [comment]
I am now fighting with that topic again for #35 and my previous discoveries doesn't seems to be of much help for the state of the config I have now.

Also forgot to link the redshift forum thread which never got a proper answer :(
https://redshift.maxon.net/topic/44651/ocio-colorspace-discovering-process-is-too-obscure
